export class ClienteModel {
  isClient: boolean =  true;
  externalId: string = null;
  customerTyp: string = null;
  customerId: string = null;
  name: string = null;
  vatNumber: string = null;
  phone: string = null;
  cell: string = null;
  email: string = null;
  postalCode: string = null;
  street: string = null;
  number: string = null;
  neighborhood: string = null;
  detail: string = null;
  city: string = null;
  uf: string = null;
  country: string = null;
  stateId: string = null;
  municipalId: string = null;
  birth: string = null;
  gender: string = null;
}
